[project]
name = "proyecto-prueba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.33.1",
    "streamlit>=1.49.1",
    "vega-datasets>=0.9.0",
]
